### ISSUE TITLE
Some Numberformat exceptions and a NPE

### ISSUE THREAD

**Issue by karussell** [AdoptOpenJDK/jitwatch#176]
Learned already a lot from jitwatch - thanks :)

Some exceptions where thrown today for master (1.0.0-SNAPSHOT) and java 1.8.0_45:

 * the first ones are probably due to my German environment:
```
23:39:21.116 [Thread-7] ERROR o.a.j.s.AttributeSuggestionWalker - Couldn't parse branch tag attribute 1,21666e+06
java.lang.NumberFormatException: For input string: "1,21666e+06"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_45]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:1.8.0_45]
        at java.lang.Double.parseDouble(Double.java:538) ~[na:1.8.0_45]
        at java.lang.Double.valueOf(Double.java:502) ~[na:1.8.0_45]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.handleBranchTag(AttributeSuggestionWalker.java:301) [jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.processParseTag(AttributeSuggestionWalker.java:193) [jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.processParseTag(AttributeSuggestionWalker.java:211) [jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.processParseTag(AttributeSuggestionWalker.java:211) [jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.visitTag(AttributeSuggestionWalker.java:367) [jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.journal.JournalUtil.visitParseTagsOfLastTask(JournalUtil.java:91) [jitwatch-1.0.0-SNAPSHOT.jar:na]


23:39:21.114 [Thread-7] ERROR o.a.j.s.AttributeSuggestionWalker - Unrecognised branch probability: 0,50343
java.lang.NumberFormatException: For input string: "0,50343"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_45]
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:1.8.0_45]
        at java.lang.Double.parseDouble(Double.java:538) ~[na:1.8.0_45]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.handleBranchTag(AttributeSuggestionWalker.java:313) [jitwatch-1.0.0-SNAPSHOT.jar:na]

```

 * And a NPE:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at org.adoptopenjdk.jitwatch.model.MetaClass.loadInnerClasses(MetaClass.java:135)
        at org.adoptopenjdk.jitwatch.model.MetaClass.getClassBytecode(MetaClass.java:112)
        at org.adoptopenjdk.jitwatch.ui.triview.TriView.loadBytecodeForCurrentMember(TriView.java:631)
        at org.adoptopenjdk.jitwatch.ui.triview.TriView.setMember(TriView.java:513)
        at org.adoptopenjdk.jitwatch.ui.triview.TriView.setMember(TriView.java:488)
        at org.adoptopenjdk.jitwatch.ui.JITWatchUI.openTriView(JITWatchUI.java:693)
        at org.adoptopenjdk.jitwatch.ui.suggestion.MemberTableCell$1.handle(MemberTableCell.java:63)
        at org.adoptopenjdk.jitwatch.ui.suggestion.MemberTableCell$1.handle(MemberTableCell.java:59)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)

```

**Comment by chriswhocodes** [comment]
Hi Peter,

Thanks for the bug report and for trying out JITWatch.

You've found a couple of places where I was using Double.parseDouble directly and not via my Locale-aware wrapper. Fixed that now and added a guard around the inner class NPE in commit  1268d63.

Please let me know if this fixes the problem?

Cheers,

Chris

**Comment by karussell** [comment]
They seem to be fixed now. Now others occur:
```
08:06:15.075 [Thread-3] ERROR o.a.j.u.ParseUtil - 
java.text.ParseException: Unparseable number: "always"
        at java.text.NumberFormat.parse(NumberFormat.java:385) ~[na:1.8.0_45]
        at org.adoptopenjdk.jitwatch.util.ParseUtil.parseLocaleSafeDouble(ParseUtil.java:130) ~[jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.handleBranchTag(AttributeSuggestionWalker.java:313) [jitwatch-1.0.0-SNAPSHOT.jar:na]

08:06:15.073 [Thread-3] ERROR o.a.j.u.ParseUtil - 
java.text.ParseException: Unparseable number: "never"
        at java.text.NumberFormat.parse(NumberFormat.java:385) ~[na:1.8.0_45]
        at org.adoptopenjdk.jitwatch.util.ParseUtil.parseLocaleSafeDouble(ParseUtil.java:130) ~[jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.suggestion.AttributeSuggestionWalker.handleBranchTag(AttributeSuggestionWalker.java:313) 
```

Also I can see a warning
`08:06:15.015 [Thread-3] WARN  o.a.j.j.JournalUtil - Unexpected parse phase count: 0`

**Comment by karussell** [comment]
BTW: thanks a lot for the very fast fix :) !

**Comment by karussell** [comment]
Also it is normal that the 'compilation timeline' chart for my 1-2 minute run shows over 36h on the x-axis - maybe another locale problem?

**Comment by chriswhocodes** [comment]
Hi Peter,

I'll have a fix for the always/never bug tonight.

The timeline bug sounds like locales as well. Any chance you could email a zipped hotspot.log to chris@chrisnewland.com?

Anything logged at WARN level is something I'm aware of but is not necessarily a bug (there's no DTD for the LogCompilation XML so it's hard to know which elements are mandatory/optional without digging deep in the VM code).

Thanks for the feedback!

Chris

**Comment by karussell** [comment]
I have done this and there is another exception probably reproducable with my log:

```
13:52:46.718 [JavaFX Application Thread] ERROR o.a.j.m.b.BytecodeAnnotationBuilder - Error building bytecode annotations
org.adoptopenjdk.jitwatch.model.LogParseException: Could not parse annotations
        at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTagParse(BytecodeAnnotationBuilder.java:130) ~[jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.model.bytecode.BytecodeAnnotationBuilder.visitTag(BytecodeAnnotationBuilder.java:104) ~[jitwatch-1.0.0-SNAPSHOT.jar:na]
        at org.adoptopenjdk.jitwatch.journal.JournalUtil.visitParseTagsOfLastTask(JournalUtil.java:90) ~[jitwatch-1.0.0-SNAPSHOT.jar:na]
```

**Comment by chriswhocodes** [comment]
Hi Peter, I think I've fixed the branch probability parsing. I've improved logging of annotation building exceptions as well.

Regarding the timestamps, I think this is caused by running JITWatch in a different locale to the one that recorded the logs.

The log timestamp is always a decimal number of seconds since VM start.

If the log file was collected running in a locale with a comma decimal separator and then parsed in a locale with a dot decimal separator then stamp="1,234" is parsed as 1234 seconds which becomes 1234000 millis.

Sadly the HotSpot log does not contain the locale so I think I'm going to have to make an assumption that a comma is always a decimal separator for a timestamp and should be replaced with a dot.

Let me know how you get on with the latest commit?

Cheers,

Chris

**Comment by karussell** [comment]
The chart x-axis seems still not fixed but no exceptions anymore :)

**Comment by chriswhocodes** [comment]
Hi Peter,

Can you let me know the value of Locale.getDefault() on the PC where you are running JITWatch?

**Comment by karussell** [comment]
Uhm, I run
`javax.swing.JOptionPane.showMessageDialog(null, "locale:" + java.util.Locale.getDefault());`

in the sandbox
(sysout is not printed therefor the workaround via swing :)) 

and I got `en_US` and a printout of double f=-1.2; as `-1.2`  ... strange. I thought it would be `de_DE` but yes my OS is set to English to prevent locale problems ;)

(timezone is Berlin)

**Comment by chriswhocodes** [comment]
OK, that explains it then. I will check if LogCompilation uses a thousands separator for large stamp values (I don't expect so). If it doesn't then I can assume UK locale and always replace comma with a dot.

**Comment by chriswhocodes** [comment]
Hi Peter,

I've found an easier solution than polluting the code.

Simply override the country and language on the command line to match the system where the log was taken:

-Duser.country=DE -Duser.language=de

Works fine with your log file.

Cheers,

Chris

**Comment by chriswhocodes** [comment]
Added a troubleshooting page with this workaround: https://github.com/AdoptOpenJDK/jitwatch/wiki/Troubleshooting

Please close the issue if this works for you?

Cheers,

Chris

**Comment by karussell** [comment]
Nice, indeed this fixed the issue for the chart!
